SET INSTALL_PATH=%CD%
SET PRJ_NAME=mysite
path = %INSTALL_PATH%\Apache2\bin;%INSTALL_PATH%\Python26;%INSTALL_PATH%\Utilities\;%INSTALL_PATH%\mssql;%PATH%
set PYTHONPATH=%1;%INSTALL_PATH%\mssql;%INSTALL_PATH%\mssql\win32\lib;%INSTALL_PATH%\Python26;%INSTALL_PATH%\Python26\Lib\site-packages;%INSTALL_PATH%
SET DJANGO_SETTINGS_MODULE=%PRJ_NAME%.settings